/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uipackage;
import business_package.vitalsignhistory;
import business_package.vitalsign;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.CardLayout;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author imperio2494
 */
public class createjpanel extends javax.swing.JPanel {

    /**
     * Creates new form createjpanel
     */
    private vitalsignhistory vitalSignHistory;
    
    private JPanel rightpanel;
    public createjpanel(JPanel rightpanel,vitalsignhistory history) {
        initComponents();
        this.vitalSignHistory=history;
        this.rightpanel=rightpanel;
        timetb.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timetb = new javax.swing.JTextField();
        respiratorytb = new javax.swing.JTextField();
        hrtb = new javax.swing.JTextField();
        bptb = new javax.swing.JTextField();
        addvitalsignBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        weightkgtb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        weightlbtb = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Create Vital Sign");

        jLabel2.setText("Respiratory Rate");

        jLabel3.setText("Heart Rate");

        jLabel4.setText("Systolic Blood Pressure");

        jLabel5.setText("Timestamp");

        timetb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetbActionPerformed(evt);
            }
        });

        respiratorytb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respiratorytbActionPerformed(evt);
            }
        });

        hrtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrtbActionPerformed(evt);
            }
        });

        addvitalsignBTN.setText("save");
        addvitalsignBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvitalsignBTNActionPerformed(evt);
            }
        });

        jLabel6.setText("Weight(Kg)");

        weightkgtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightkgtbActionPerformed(evt);
            }
        });

        jLabel7.setText("Weight(lb)");

        weightlbtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightlbtbActionPerformed(evt);
            }
        });

        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 339, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hrtb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bptb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(respiratorytb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(timetb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(weightlbtb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(weightkgtb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(281, 281, 281))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addvitalsignBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backbtn))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(respiratorytb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hrtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(bptb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timetb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(weightkgtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(weightlbtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(40, 40, 40)
                .addComponent(addvitalsignBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hrtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrtbActionPerformed

    private void respiratorytbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respiratorytbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respiratorytbActionPerformed

    private void timetbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timetbActionPerformed

    private void addvitalsignBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvitalsignBTNActionPerformed
        double bp,hr,rr,wkg,wlb;
        String error_string="";
        try{
        bp=Double.parseDouble(bptb.getText());
        
        }
        catch(Exception e)
        {
            error_string=error_string+" blood pressure,";
        
        }
        try{
        hr=Double.parseDouble(hrtb.getText());
        }
        catch(Exception e1){
        error_string=error_string+" heart rate,";
        }
        try{
        rr=Double.parseDouble(respiratorytb.getText());
        }
        catch(Exception e2){
        error_string=error_string+" respiratory rate,";
        }
        
        try{
        wkg=Double.parseDouble(weightkgtb.getText());
        }
        catch(Exception e3){
        error_string=error_string+" weight in kgs,";
        
        }
        
        try{
        wlb=Double.parseDouble(weightlbtb.getText());
        }
        catch(Exception e4){
        
        error_string=error_string+" weight in lbs";
        }
        
        if(error_string.trim().length()>1){
        JOptionPane.showMessageDialog(null, "Please check the following fields again:\n"+error_string);
        }
        else{
        vitalsign vitalSign = vitalSignHistory.addnewvitalsign();
        vitalSign.setBp(Double.parseDouble(bptb.getText()));
        vitalSign.setHeartRate(Double.parseDouble(hrtb.getText()));
        vitalSign.setRespiratoryRate(Double.parseDouble(respiratorytb.getText()));
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String date  = dateFormat.format(new Date());
        vitalSign.setTimestamp(date);
        vitalSign.setWeightinkg(Double.parseDouble(weightkgtb.getText()));
        vitalSign.setWeightinlbs(Double.parseDouble(weightlbtb.getText()));
        

        
        JOptionPane.showMessageDialog(null, "create success");}
    }//GEN-LAST:event_addvitalsignBTNActionPerformed

    private void weightkgtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightkgtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightkgtbActionPerformed

    private void weightlbtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightlbtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightlbtbActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
      
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addvitalsignBTN;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField bptb;
    private javax.swing.JTextField hrtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField respiratorytb;
    private javax.swing.JTextField timetb;
    private javax.swing.JTextField weightkgtb;
    private javax.swing.JTextField weightlbtb;
    // End of variables declaration//GEN-END:variables
}
