/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uipackage;

import business_package.vitalsign;
import javax.swing.JPanel;

/**
 *
 * @author imperio2494
 */
public class viewvitalsign extends javax.swing.JPanel {

    /**
     * Creates new form viewvitalsign
     */
    private vitalsign vitalSign;
    private JPanel rightpanel;
    public viewvitalsign(JPanel rightpanel,vitalsign vitalsigninstance) {
        initComponents();
        this.rightpanel=rightpanel;
        this.vitalSign=vitalsigninstance;
        populatevitalsignscreen();
    }
    
    
    public void populatevitalsignscreen(){
    resptb.setText(Double.toString(vitalSign.getRespiratoryRate()));
    hrtb.setText(Double.toString(vitalSign.getHeartRate()));
    bptb.setText(Double.toString(vitalSign.getBp()));
    timetb.setText(vitalSign.getTimestamp());
    weigkgtb.setText(Double.toString(vitalSign.getWeightinkg()));
    weiglbtb.setText(Double.toString(vitalSign.getWeightinlbs()));
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timetb = new javax.swing.JTextField();
        resptb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        weigkgtb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        weiglbtb = new javax.swing.JTextField();
        hrtb = new javax.swing.JTextField();
        bptb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel2.setText("Respiratory Rate");

        jLabel3.setText("Heart Rate");

        jLabel4.setText("Systolic Blood Pressure");

        jLabel5.setText("Timestamp");

        timetb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetbActionPerformed(evt);
            }
        });

        resptb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resptbActionPerformed(evt);
            }
        });

        jLabel6.setText("Weight(Kg)");

        weigkgtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weigkgtbActionPerformed(evt);
            }
        });

        jLabel7.setText("Weight(lb)");

        weiglbtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weiglbtbActionPerformed(evt);
            }
        });

        hrtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrtbActionPerformed(evt);
            }
        });

        jLabel1.setText("Vital Sign");

        updatebtn.setText("update");

        savebtn.setText("save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jButton3.setText("<<Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(updatebtn)
                .addGap(75, 75, 75)
                .addComponent(savebtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(96, 96, 96)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hrtb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bptb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resptb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timetb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weiglbtb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(weigkgtb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(49, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebtn)
                    .addComponent(savebtn))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(resptb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hrtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(bptb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(timetb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(weigkgtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(weiglbtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(54, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void timetbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timetbActionPerformed

    private void resptbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resptbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resptbActionPerformed

    private void weigkgtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weigkgtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weigkgtbActionPerformed

    private void weiglbtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weiglbtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weiglbtbActionPerformed

    private void hrtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrtbActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
    vitalSign.setBp(Double.parseDouble(resptb.getText()));
    vitalSign.setHeartRate(Double.parseDouble(hrtb.getText()));
    vitalSign.setRespiratoryRate(Double.parseDouble(resptb.getText()));
    vitalSign.setTimestamp(timetb.getText());
    vitalSign.setWeightinkg(Double.parseDouble(weigkgtb.getText()));
    vitalSign.setWeightinlbs(Double.parseDouble(weiglbtb.getText()));
    populatevitalsignscreen();
    }//GEN-LAST:event_savebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bptb;
    private javax.swing.JTextField hrtb;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField resptb;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField timetb;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField weigkgtb;
    private javax.swing.JTextField weiglbtb;
    // End of variables declaration//GEN-END:variables
}
