/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uipackage;
import business_package.patient;
import business_package.patient_directory;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
/**
 *
 * @author imperio2494
 */





public class viewallpatients extends javax.swing.JPanel {
    private JPanel rightpanel;
    private patient_directory patientDirectory;
    /**
     * Creates new form viewallpatients
     */
    public viewallpatients(JPanel rightpanel,patient_directory patientdirectory) {
        initComponents();
        this.rightpanel = rightpanel;
        this.patientDirectory=patientdirectory;
        populate();
    }
   
    
    
    private void populate(){
        
        DefaultTableModel model = (DefaultTableModel) directorytbl.getModel();
        Object rowdata[]=new Object[6];
        model.setRowCount(0);
        for(patient i:patientDirectory.getPatientDirectory() ){
        rowdata[0] = i;
        rowdata[1] = i.getPatName();
        rowdata[2] = i.getDob();
        rowdata[3] = i.getContact();
        rowdata[4] = i.getDocFirstName();
        rowdata[5] = i.getDocLastName();
        model.addRow(rowdata);
        }
        
        
        

        
        
//        model.setColumnCount(6);
//        model.setRowCount(patientDirectory.getPatientDirectory().size());
//        directorytbl.setAutoCreateRowSorter(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        directorytbl = new javax.swing.JTable();
        viewpatient = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jLabel1.setText("Patient Directory");

        directorytbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "name", "date of birth", "contact", "doctor first name", "doctor last name"
            }
        ));
        jScrollPane1.setViewportView(directorytbl);

        viewpatient.setText("view");
        viewpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpatientActionPerformed(evt);
            }
        });

        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        deletebtn.setText("delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(227, 227, 227)
                        .addComponent(backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deletebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewpatient)
                                .addGap(56, 56, 56))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpatient)
                    .addComponent(deletebtn))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpatientActionPerformed
                // TODO add your handling code here:
        int index = directorytbl.getSelectedRow();
//        System.out.print(directorytbl.getValueAt(index, 0));
        patient pat = (patient)directorytbl.getValueAt(index, 0);
        viewPatient viewpatient=new viewPatient(rightpanel, pat);  
        rightpanel.add("viewpatientpanel",viewpatient);
        CardLayout layout=(CardLayout)rightpanel.getLayout();
        layout.next(rightpanel);
        
//        patientDirectory.deletepatient(prod);
//        populate();
        
    }//GEN-LAST:event_viewpatientActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        int index = directorytbl.getSelectedRow();
//        System.out.print(directorytbl.getValueAt(index, 0));
        patient pat = (patient)directorytbl.getValueAt(index, 0);
        patientDirectory.deletepatient(pat);
        populate();
    }//GEN-LAST:event_deletebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
        
        Component[] comps=rightpanel.getComponents();
        for(Component c:comps){
        if(c instanceof viewallpatients){
        viewallpatients panel = (viewallpatients)c;
        panel.populate();
        }
        }
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTable directorytbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewpatient;
    // End of variables declaration//GEN-END:variables
}
