/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uipackage;

import business_package.vitalsign;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author imperio2494
 */
public class viewvitalsign extends javax.swing.JPanel {

    /**
     * Creates new form viewvitalsign
     */
    private vitalsign vitalSign;
    private JPanel rightpanel;
    public viewvitalsign(JPanel rightpanel,vitalsign vitalsigninstance) {
        initComponents();
        this.rightpanel=rightpanel;
        this.vitalSign=vitalsigninstance;
        populatevitalsignscreen();
    }
    
    
    public void populatevitalsignscreen(){
        
    updatebtn.setEnabled(true);
    savebtn.setEnabled(false);
    hrtb.setEditable(false);
    resptb.setEditable(false);
    bptb.setEditable(false);
    timetb.setEditable(false);
    weigkgtb.setEditable(false);
    weiglbtb.setEditable(false);
    
    
    resptb.setText(Double.toString(vitalSign.getRespiratoryRate()));
    hrtb.setText(Double.toString(vitalSign.getHeartRate()));
    bptb.setText(Double.toString(vitalSign.getBp()));
//    timetb.setText(vitalSign.getTimestamp());
    weigkgtb.setText(Double.toString(vitalSign.getWeightinkg()));
    weiglbtb.setText(Double.toString(vitalSign.getWeightinlbs()));
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timetb = new javax.swing.JTextField();
        resptb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        weigkgtb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        weiglbtb = new javax.swing.JTextField();
        hrtb = new javax.swing.JTextField();
        bptb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        jLabel2.setText("Respiratory Rate");

        jLabel3.setText("Heart Rate");

        jLabel4.setText("Systolic Blood Pressure");

        jLabel5.setText("Timestamp");

        timetb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetbActionPerformed(evt);
            }
        });

        resptb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resptbActionPerformed(evt);
            }
        });

        jLabel6.setText("Weight(Kg)");

        weigkgtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weigkgtbActionPerformed(evt);
            }
        });

        jLabel7.setText("Weight(lb)");

        weiglbtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weiglbtbActionPerformed(evt);
            }
        });

        hrtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrtbActionPerformed(evt);
            }
        });

        jLabel1.setText("Vital Sign");

        updatebtn.setText("update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        savebtn.setText("save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resptb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weigkgtb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weiglbtb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timetb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bptb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrtb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(jLabel1)
                        .addGap(91, 91, 91)
                        .addComponent(backbtn)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backbtn)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resptb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bptb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timetb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weigkgtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weiglbtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebtn)
                    .addComponent(savebtn))
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void timetbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timetbActionPerformed

    private void resptbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resptbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resptbActionPerformed

    private void weigkgtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weigkgtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weigkgtbActionPerformed

    private void weiglbtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weiglbtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weiglbtbActionPerformed

    private void hrtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrtbActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        
    double bp,hr,rr,wkg,wlb;
        String error_string="";
        try{
        bp=Double.parseDouble(bptb.getText());
        
        }
        catch(Exception e)
        {
            error_string=error_string+" blood pressure,";
        
        }
        try{
        hr=Double.parseDouble(hrtb.getText());
        }
        catch(Exception e1){
        error_string=error_string+" heart rate,";
        }
        try{
        rr=Double.parseDouble(resptb.getText());
        }
        catch(Exception e2){
        error_string=error_string+" respiratory rate,";
        }
        
        try{
        wkg=Double.parseDouble(weigkgtb.getText());
        }
        catch(Exception e3){
        error_string=error_string+" weight in kgs,";
        
        }
        
        try{
        wlb=Double.parseDouble(weiglbtb.getText());
        }
        catch(Exception e4){
        
        error_string=error_string+" weight in lbs";
        }
        
        if(error_string.trim().length()>0){
        JOptionPane.showMessageDialog(null, "Please check the following fields again:\n"+error_string);
        }
        else{
        
        vitalSign.setBp(Double.parseDouble(bptb.getText()));
        vitalSign.setHeartRate(Double.parseDouble(hrtb.getText()));
        vitalSign.setRespiratoryRate(Double.parseDouble(resptb.getText()));
        vitalSign.setWeightinkg(Double.parseDouble(weigkgtb.getText()));
        vitalSign.setWeightinlbs(Double.parseDouble(weiglbtb.getText()));
        

        
        JOptionPane.showMessageDialog(null, "updated successfully");
        
        
        }
        populatevitalsignscreen();
         
//    vitalSign.setBp(Double.parseDouble(resptb.getText()));
//    vitalSign.setHeartRate(Double.parseDouble(hrtb.getText()));
//    vitalSign.setRespiratoryRate(Double.parseDouble(resptb.getText()));
//    vitalSign.setTimestamp(timetb.getText());
//    vitalSign.setWeightinkg(Double.parseDouble(weigkgtb.getText()));
//    vitalSign.setWeightinlbs(Double.parseDouble(weiglbtb.getText()));
    
    }//GEN-LAST:event_savebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        
        updatebtn.setEnabled(false);
    savebtn.setEnabled(true);
    hrtb.setEditable(true);
    resptb.setEditable(true);
    bptb.setEditable(true);
    timetb.setEditable(true);
    weigkgtb.setEditable(true);
    weiglbtb.setEditable(true);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField bptb;
    private javax.swing.JTextField hrtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField resptb;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField timetb;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField weigkgtb;
    private javax.swing.JTextField weiglbtb;
    // End of variables declaration//GEN-END:variables
}
