/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uipackage;

/**
 *
 * @author imperio2494
 */
import javax.swing.table.DefaultTableModel;
import business_package.vitalsign;
import business_package.vitalsignhistory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.*;
public class viewpanel extends javax.swing.JPanel {

    /**
     * Creates new form viewpanel
     */
    vitalsignhistory vitalSignHistory;
    JPanel rightpanel;
    Myrenderer r;
    public viewpanel(JPanel rightpanel, vitalsignhistory vitalsignhistory ) {
        initComponents();
        this.rightpanel = rightpanel;
        this.vitalSignHistory=vitalsignhistory;
        this.r=new Myrenderer();
        populate();
        
        
    }
    
    private void populate(){
        refreshTableRendering();
        DefaultTableModel model = (DefaultTableModel) historyTbl.getModel();
        Object rowdata[]=new Object[6];
        model.setRowCount(0);
        for(vitalsign i:vitalSignHistory.getVitalSignHistory()){
        rowdata[0] = i;
        rowdata[1] = i.getBp();
        rowdata[2] = i.getRespiratoryRate();
        rowdata[3] = i.getHeartRate();
        rowdata[4] = i.getWeightinkg();
        rowdata[5] = i.getWeightinlbs();
        model.addRow(rowdata);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTbl = new javax.swing.JTable();
        deleteBTN = new javax.swing.JButton();
        detailsBTN = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lowhr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        highhr = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("vital sign history");

        historyTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure", "respiratory rate", "heart rate", "weight(kgs)", "weight(lbs)"
            }
        ));
        historyTbl.setGridColor(new java.awt.Color(10, 255, 255));
        historyTbl.setSelectionForeground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setViewportView(historyTbl);

        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        detailsBTN.setText("details");
        detailsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsBTNActionPerformed(evt);
            }
        });

        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Abnormal heart rate");

        lowhr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowhrActionPerformed(evt);
            }
        });
        lowhr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lowhrKeyReleased(evt);
            }
        });

        jLabel3.setText("-");

        highhr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highhrActionPerformed(evt);
            }
        });
        highhr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                highhrKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130)
                .addComponent(backbtn)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(detailsBTN)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 143, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lowhr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(highhr, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backbtn))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsBTN)
                    .addComponent(deleteBTN))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lowhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(highhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        int i = historyTbl.getSelectedRow();
        vitalsign vitalSignfordeletion = (vitalsign)historyTbl.getValueAt(i, 0);
        vitalSignHistory.deletevitalsign(vitalSignfordeletion);
        populate();
        

    }//GEN-LAST:event_deleteBTNActionPerformed

    private void detailsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsBTNActionPerformed
        int index = historyTbl.getSelectedRow();
        vitalsign vs=(vitalsign) historyTbl.getValueAt(index, 0);
        viewvitalsign viewvitalsignpanel= new viewvitalsign(rightpanel,vs);
        rightpanel.add("viewvitalsignpanel",viewvitalsignpanel);
        CardLayout layout=(CardLayout)rightpanel.getLayout();
        layout.next(rightpanel);
        
//        vitalsign dataobj = historyglbl.getVitalSignHistory().get(i);
//        temperatureTB.setText(String.valueOf(dataobj.getTemperature()));
//        bpTB.setText(String.valueOf(dataobj.getTemperature()));
//        pulseTB.setText(String.valueOf(dataobj.getPulse()));
//        dateTB.setText(dataobj.getDate());
    }//GEN-LAST:event_detailsBTNActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here: 
        rightpanel.remove(this);
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
        
        Component[] comps=rightpanel.getComponents();
        for(Component c:comps){
        if(c instanceof viewpanel){
        viewpanel panel = (viewpanel)c;
        panel.populate();
        }
        }
    }//GEN-LAST:event_backbtnActionPerformed

    private void lowhrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowhrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowhrActionPerformed

    private void lowhrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lowhrKeyReleased
        // TODO add your handling code here:
        
        populate();
    }//GEN-LAST:event_lowhrKeyReleased

    private void highhrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_highhrKeyReleased
        // TODO add your handling code here:
        populate();
    }//GEN-LAST:event_highhrKeyReleased

    private void highhrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highhrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highhrActionPerformed
    
    private void refreshTableRendering(){
        r.clearpair();
        historyTbl.setDefaultRenderer(Object.class,r);
        if(highhr.getText().trim().length()>0 && lowhr.getText().trim().length()>0)
        {
            
        double low=Double.parseDouble(lowhr.getText());
        double high=Double.parseDouble(highhr.getText());
        int i=0;
        for(vitalsign item:vitalSignHistory.getVitalSignHistory()){
            if (!item.isNormal(low,high)){
                r.addpair(i,3);
            
            }
            ++i;
        }

}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton detailsBTN;
    private javax.swing.JTextField highhr;
    private javax.swing.JTable historyTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lowhr;
    // End of variables declaration//GEN-END:variables
}
