/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uipackage;

import business_package.patient;
import javax.swing.JPanel;
import business_package.vitalsignhistory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
/**
 *
 * @author imperio2494
 */
public class viewPatient extends javax.swing.JPanel {
    private patient Patient;
    private JPanel rightpanel;
    /**
     * Creates new form viewPatient
     */
    public viewPatient(JPanel rightpanel,patient patient) {
        initComponents();
        this.Patient=patient;
        this.rightpanel=rightpanel;
        populatePatientDetails();
        
    }
    
    private void populatePatientDetails(){
    updatepatientbtn.setEnabled(true);
    savepatientbtn.setEnabled(false);
    idtb.setEditable(false);
    nametb.setEditable(false);
    dobtb.setEditable(false);
    contacttb.setEditable(false);
    pharmatb.setEditable(false);
    docfnametb.setEditable(false);
    doclnametb.setEditable(false);
    
    idtb.setText(Integer.toString(Patient.getPatId()));
    nametb.setText(Patient.getPatName());
    dobtb.setText(Patient.getDob());
    contacttb.setText(Patient.getContact());
    pharmatb.setText(Patient.getPharmacyName());
    docfnametb.setText(Patient.getDocFirstName());
    doclnametb.setText(Patient.getDocLastName());
          
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        docfnametb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        doclnametb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idtb = new javax.swing.JTextField();
        nametb = new javax.swing.JTextField();
        dobtb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        contacttb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pharmatb = new javax.swing.JTextField();
        updatepatientbtn = new javax.swing.JButton();
        savepatientbtn = new javax.swing.JButton();
        addvitalsignbtn = new javax.swing.JButton();
        viewvitalsign = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        jLabel3.setText("name");

        jLabel4.setText("contact/phone");

        jLabel5.setText("dob");

        jLabel6.setText("preferred pharmacy");

        jLabel7.setText("primary doctor last name");

        jLabel8.setText("primary doctor first name");

        jLabel1.setText("View Patient");

        contacttb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacttbActionPerformed(evt);
            }
        });

        jLabel2.setText("id");

        updatepatientbtn.setText("update");
        updatepatientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepatientbtnActionPerformed(evt);
            }
        });

        savepatientbtn.setText("save");
        savepatientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savepatientbtnActionPerformed(evt);
            }
        });

        addvitalsignbtn.setText("Add Vital Sign");
        addvitalsignbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvitalsignbtnActionPerformed(evt);
            }
        });

        viewvitalsign.setText("View Vital Signs");
        viewvitalsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewvitalsignActionPerformed(evt);
            }
        });

        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(36, 36, 36))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updatepatientbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idtb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nametb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobtb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contacttb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pharmatb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(docfnametb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doclnametb)
                            .addComponent(savepatientbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewvitalsign, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addvitalsignbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nametb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dobtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contacttb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pharmatb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(docfnametb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(addvitalsignbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(viewvitalsign, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doclnametb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatepatientbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savepatientbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contacttbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacttbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacttbActionPerformed

    private void updatepatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepatientbtnActionPerformed
        // TODO add your handling code here:
        updatepatientbtn.setEnabled(false);
        savepatientbtn.setEnabled(true);
        
    nametb.setEditable(true);
    dobtb.setEditable(true);
    contacttb.setEditable(true);
    pharmatb.setEditable(true);
    docfnametb.setEditable(true);
    doclnametb.setEditable(true);
        
    }//GEN-LAST:event_updatepatientbtnActionPerformed

    private void savepatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savepatientbtnActionPerformed
        // TODO add your handling code here:
        
        String errorString="";
        
        String name=nametb.getText().trim();
        if (name.length()<=0)
            errorString=errorString+" name ,";
        String dob=dobtb.getText();
        if (dob.length()<=0)
            errorString=errorString+" Date of Birth ,";
        
        
         String    contact=contacttb.getText().trim();
       
            
        String pharma=pharmatb.getText().trim();
        String docfname=docfnametb.getText().trim();
        if (docfname.length()<=0)
            errorString=errorString+" doctor's first name ,";
        String doclname=doclnametb.getText();
        if (doclname.length()<=0)
            errorString=errorString+" doctor's last name ";
        
        if(errorString.trim().length()>1)
            JOptionPane.showMessageDialog(null,"Please check the fields properly:\n"+errorString);
        else{
            
            Patient.setPatName(name);
        Patient.setDob(dob);
        Patient.setContact(contact);
        Patient.setDocFirstName(docfname);
        Patient.setDocLastName(doclname);
        
        Patient.setPharmacyName(pharma);
        
        JOptionPane.showMessageDialog(null," patient updated successfully");
        }
        populatePatientDetails();
        
        
        
        
//        Patient.setPatName(nametb.getText());
//        Patient.setDob(dobtb.getText());
//        Patient.setContact(contacttb.getText());
//        Patient.setPharmacyName(pharmatb.getText());
//        Patient.setDocFirstName(docfnametb.getText());
//        Patient.setDocLastName(doclnametb.getText());
        
    }//GEN-LAST:event_savepatientbtnActionPerformed

    private void addvitalsignbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvitalsignbtnActionPerformed
        vitalsignhistory vitalSignHistory = Patient.getVitalSignHistory();
        createjpanel createVsPanel=new createjpanel(rightpanel,vitalSignHistory);
        rightpanel.add("createvitalsignpanel",createVsPanel);
        CardLayout layout=(CardLayout)rightpanel.getLayout();
        layout.next(rightpanel);
    }//GEN-LAST:event_addvitalsignbtnActionPerformed

    private void viewvitalsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewvitalsignActionPerformed
        vitalsignhistory vitalSignHistory = Patient.getVitalSignHistory();
        viewpanel viewvitalsignpanel=new viewpanel(rightpanel, vitalSignHistory);
        rightpanel.add("viewvitalsignpanel",viewvitalsignpanel);
        CardLayout layout=(CardLayout)rightpanel.getLayout();
        layout.next(rightpanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewvitalsignActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addvitalsignbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField contacttb;
    private javax.swing.JTextField dobtb;
    private javax.swing.JTextField docfnametb;
    private javax.swing.JTextField doclnametb;
    private javax.swing.JTextField idtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nametb;
    private javax.swing.JTextField pharmatb;
    private javax.swing.JButton savepatientbtn;
    private javax.swing.JButton updatepatientbtn;
    private javax.swing.JButton viewvitalsign;
    // End of variables declaration//GEN-END:variables
}
